
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-5pm-6
owner: ucsb-cs156-s24
repo_name: team01-s24-5pm-6
pull_requests: [{"author":{"id":"U_kgDOB0qzkg","is_bot":false,"login":"lindseywn","name":""},"headRefName":"Lindsey-University-Controller","number":26,"title":"Add University Controller and Test","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-6/pull/26"},{"author":{"id":"MDQ6VXNlcjU1NjAyNjE0","is_bot":false,"login":"jeffsmithepic","name":"wchiba"},"headRefName":"Wesley-PublicHoliday-Controller","number":24,"title":"Implement Public Holiday Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-6/pull/24"},{"author":{"id":"U_kgDOB0qzkg","is_bot":false,"login":"lindseywn","name":""},"headRefName":"Lindsey-University","number":23,"title":"Add university service ","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-6/pull/23"},{"author":{"id":"U_kgDOBX3DZA","is_bot":false,"login":"yuji-sakaguchi","name":"Yuji Sakaguchi"},"headRefName":"Yuji-Tides","number":22,"title":"Add Tides Service","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-6/pull/22"},{"author":{"id":"MDQ6VXNlcjcyNzc3NTIz","is_bot":false,"login":"diyaparm","name":""},"headRefName":"Diya-Joke-Controller","number":21,"title":"Diya joke controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-6/pull/21"},{"author":{"id":"MDQ6VXNlcjU1NjAyNjE0","is_bot":false,"login":"jeffsmithepic","name":"wchiba"},"headRefName":"Wesley-PublicHoliday","number":19,"title":"Implement Holiday Query Service","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-6/pull/19"},{"author":{"id":"MDQ6VXNlcjcyNzc3NTIz","is_bot":false,"login":"diyaparm","name":""},"headRefName":"Diya-Joke","number":18,"title":"Diya joke","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-6/pull/18"}]
